version: '3.6'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    restart: always
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=4818115
      - POSTGRESQL_DATABASE=hack2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql.data
    network_mode: "host"
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    restart: always
    network_mode: "host"

volumes:
  postgres-data: